//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model", "ReservaLocal", "Reserva", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Integer.Import.Reserva), "Local", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Integer.Import.Local))]
[assembly: EdmRelationshipAttribute("Model", "EventoGrupo", "Evento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Integer.Import.Evento), "Grupo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Integer.Import.Grupo))]
[assembly: EdmRelationshipAttribute("Model", "EventoConflito", "Evento", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Integer.Import.Evento), "Conflito", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Integer.Import.Conflito))]
[assembly: EdmRelationshipAttribute("Model", "ConflitoEvento", "Conflito", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Integer.Import.Conflito), "Evento", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Integer.Import.Evento))]
[assembly: EdmRelationshipAttribute("Model", "EventoReserva", "Evento", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Integer.Import.Evento), "Reserva", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Integer.Import.Reserva))]
[assembly: EdmRelationshipAttribute("Model", "SolicitacaoAcessoGrupo", "SolicitacaoAcesso", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Integer.Import.SolicitacaoAcesso), "Grupo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Integer.Import.Grupo))]
[assembly: EdmRelationshipAttribute("Model", "UsuarioSolicitacaoAcesso", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Integer.Import.Usuario), "SolicitacaoAcesso", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Integer.Import.SolicitacaoAcesso))]
[assembly: EdmRelationshipAttribute("Model", "UsuarioAtuacaoNoGrupo", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Integer.Import.Usuario), "AtuacaoNoGrupo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Integer.Import.AtuacaoNoGrupo))]
[assembly: EdmRelationshipAttribute("Model", "AtuacaoNoGrupoGrupo", "AtuacaoNoGrupo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Integer.Import.AtuacaoNoGrupo), "Grupo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Integer.Import.Grupo))]
[assembly: EdmRelationshipAttribute("Model", "GrupoGrupo", "Grupo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Integer.Import.Grupo), "Grupo1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Integer.Import.Grupo))]
[assembly: EdmRelationshipAttribute("Model", "EventoPublicoAlvo", "Evento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Integer.Import.Evento), "PublicoAlvo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Integer.Import.PublicoAlvo))]

#endregion

namespace Integer.Import
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AgendaContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AgendaContainer object using the connection string found in the 'AgendaContainer' section of the application configuration file.
        /// </summary>
        public AgendaContainer() : base("name=AgendaContainer", "AgendaContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AgendaContainer object.
        /// </summary>
        public AgendaContainer(string connectionString) : base(connectionString, "AgendaContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AgendaContainer object.
        /// </summary>
        public AgendaContainer(EntityConnection connection) : base(connection, "AgendaContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Local> Local
        {
            get
            {
                if ((_Local == null))
                {
                    _Local = base.CreateObjectSet<Local>("Local");
                }
                return _Local;
            }
        }
        private ObjectSet<Local> _Local;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Grupo> Grupo
        {
            get
            {
                if ((_Grupo == null))
                {
                    _Grupo = base.CreateObjectSet<Grupo>("Grupo");
                }
                return _Grupo;
            }
        }
        private ObjectSet<Grupo> _Grupo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Evento> Evento
        {
            get
            {
                if ((_Evento == null))
                {
                    _Evento = base.CreateObjectSet<Evento>("Evento");
                }
                return _Evento;
            }
        }
        private ObjectSet<Evento> _Evento;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Reserva> Reserva
        {
            get
            {
                if ((_Reserva == null))
                {
                    _Reserva = base.CreateObjectSet<Reserva>("Reserva");
                }
                return _Reserva;
            }
        }
        private ObjectSet<Reserva> _Reserva;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Conflito> Conflito
        {
            get
            {
                if ((_Conflito == null))
                {
                    _Conflito = base.CreateObjectSet<Conflito>("Conflito");
                }
                return _Conflito;
            }
        }
        private ObjectSet<Conflito> _Conflito;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuario
        {
            get
            {
                if ((_Usuario == null))
                {
                    _Usuario = base.CreateObjectSet<Usuario>("Usuario");
                }
                return _Usuario;
            }
        }
        private ObjectSet<Usuario> _Usuario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SolicitacaoAcesso> SolicitacaoAcesso
        {
            get
            {
                if ((_SolicitacaoAcesso == null))
                {
                    _SolicitacaoAcesso = base.CreateObjectSet<SolicitacaoAcesso>("SolicitacaoAcesso");
                }
                return _SolicitacaoAcesso;
            }
        }
        private ObjectSet<SolicitacaoAcesso> _SolicitacaoAcesso;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AtuacaoNoGrupo> AtuacaoNoGrupo
        {
            get
            {
                if ((_AtuacaoNoGrupo == null))
                {
                    _AtuacaoNoGrupo = base.CreateObjectSet<AtuacaoNoGrupo>("AtuacaoNoGrupo");
                }
                return _AtuacaoNoGrupo;
            }
        }
        private ObjectSet<AtuacaoNoGrupo> _AtuacaoNoGrupo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PublicoAlvo> PublicoAlvo
        {
            get
            {
                if ((_PublicoAlvo == null))
                {
                    _PublicoAlvo = base.CreateObjectSet<PublicoAlvo>("PublicoAlvo");
                }
                return _PublicoAlvo;
            }
        }
        private ObjectSet<PublicoAlvo> _PublicoAlvo;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Local EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLocal(Local local)
        {
            base.AddObject("Local", local);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Grupo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGrupo(Grupo grupo)
        {
            base.AddObject("Grupo", grupo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Evento EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEvento(Evento evento)
        {
            base.AddObject("Evento", evento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Reserva EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReserva(Reserva reserva)
        {
            base.AddObject("Reserva", reserva);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Conflito EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConflito(Conflito conflito)
        {
            base.AddObject("Conflito", conflito);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SolicitacaoAcesso EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSolicitacaoAcesso(SolicitacaoAcesso solicitacaoAcesso)
        {
            base.AddObject("SolicitacaoAcesso", solicitacaoAcesso);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AtuacaoNoGrupo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAtuacaoNoGrupo(AtuacaoNoGrupo atuacaoNoGrupo)
        {
            base.AddObject("AtuacaoNoGrupo", atuacaoNoGrupo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PublicoAlvo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPublicoAlvo(PublicoAlvo publicoAlvo)
        {
            base.AddObject("PublicoAlvo", publicoAlvo);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="AtuacaoNoGrupo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AtuacaoNoGrupo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AtuacaoNoGrupo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="ehCoordenador">Initial value of the EhCoordenador property.</param>
        public static AtuacaoNoGrupo CreateAtuacaoNoGrupo(global::System.Int32 id, global::System.Boolean ehCoordenador)
        {
            AtuacaoNoGrupo atuacaoNoGrupo = new AtuacaoNoGrupo();
            atuacaoNoGrupo.Id = id;
            atuacaoNoGrupo.EhCoordenador = ehCoordenador;
            return atuacaoNoGrupo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            protected set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EhCoordenador
        {
            get
            {
                return _EhCoordenador;
            }
            private set
            {
                OnEhCoordenadorChanging(value);
                ReportPropertyChanging("EhCoordenador");
                _EhCoordenador = StructuralObject.SetValidValue(value, "EhCoordenador");
                ReportPropertyChanged("EhCoordenador");
                OnEhCoordenadorChanged();
            }
        }
        private global::System.Boolean _EhCoordenador;
        partial void OnEhCoordenadorChanging(global::System.Boolean value);
        partial void OnEhCoordenadorChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "AtuacaoNoGrupoGrupo", "Grupo")]
        public Grupo Grupo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("Model.AtuacaoNoGrupoGrupo", "Grupo").Value;
            }
            private set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("Model.AtuacaoNoGrupoGrupo", "Grupo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Grupo> GrupoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("Model.AtuacaoNoGrupoGrupo", "Grupo");
            }
            private set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Grupo>("Model.AtuacaoNoGrupoGrupo", "Grupo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Conflito")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Conflito : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Conflito object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="data">Initial value of the Data property.</param>
        public static Conflito CreateConflito(global::System.Int32 id, global::System.DateTime data)
        {
            Conflito conflito = new Conflito();
            conflito.Id = id;
            conflito.Data = data;
            return conflito;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            protected set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        private global::System.Int32 idMotivo
        {
            get
            {
                return _idMotivo;
            }
            set
            {
                OnidMotivoChanging(value);
                ReportPropertyChanging("idMotivo");
                _idMotivo = StructuralObject.SetValidValue(value, "idMotivo");
                ReportPropertyChanged("idMotivo");
                OnidMotivoChanged();
            }
        }
        private global::System.Int32 _idMotivo;
        partial void OnidMotivoChanging(global::System.Int32 value);
        partial void OnidMotivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Data
        {
            get
            {
                return _Data;
            }
            private set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value, "Data");
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private global::System.DateTime _Data;
        partial void OnDataChanging(global::System.DateTime value);
        partial void OnDataChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "ConflitoEvento", "Evento")]
        public Evento Evento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Evento>("Model.ConflitoEvento", "Evento").Value;
            }
            private set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Evento>("Model.ConflitoEvento", "Evento").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Evento> EventoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Evento>("Model.ConflitoEvento", "Evento");
            }
            private set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Evento>("Model.ConflitoEvento", "Evento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Evento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Evento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Evento object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="dataInicio">Initial value of the DataInicio property.</param>
        /// <param name="dataFim">Initial value of the DataFim property.</param>
        /// <param name="dataCadastro">Initial value of the DataCadastro property.</param>
        public static Evento CreateEvento(global::System.Int64 id, global::System.String nome, global::System.DateTime dataInicio, global::System.DateTime dataFim, global::System.DateTime dataCadastro)
        {
            Evento evento = new Evento();
            evento.Id = id;
            evento.Nome = nome;
            evento.DataInicio = dataInicio;
            evento.DataFim = dataFim;
            evento.DataCadastro = dataCadastro;
            return evento;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            protected set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            private set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false, "Nome");
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descricao
        {
            get
            {
                return _Descricao;
            }
            private set
            {
                OnDescricaoChanging(value);
                ReportPropertyChanging("Descricao");
                _Descricao = StructuralObject.SetValidValue(value, true, "Descricao");
                ReportPropertyChanged("Descricao");
                OnDescricaoChanged();
            }
        }
        private global::System.String _Descricao;
        partial void OnDescricaoChanging(global::System.String value);
        partial void OnDescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataInicio
        {
            get
            {
                return _DataInicio;
            }
            private set
            {
                OnDataInicioChanging(value);
                ReportPropertyChanging("DataInicio");
                _DataInicio = StructuralObject.SetValidValue(value, "DataInicio");
                ReportPropertyChanged("DataInicio");
                OnDataInicioChanged();
            }
        }
        private global::System.DateTime _DataInicio;
        partial void OnDataInicioChanging(global::System.DateTime value);
        partial void OnDataInicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataFim
        {
            get
            {
                return _DataFim;
            }
            private set
            {
                OnDataFimChanging(value);
                ReportPropertyChanging("DataFim");
                _DataFim = StructuralObject.SetValidValue(value, "DataFim");
                ReportPropertyChanged("DataFim");
                OnDataFimChanged();
            }
        }
        private global::System.DateTime _DataFim;
        partial void OnDataFimChanging(global::System.DateTime value);
        partial void OnDataFimChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        private global::System.Int32 idTipo
        {
            get
            {
                return _idTipo;
            }
            set
            {
                OnidTipoChanging(value);
                ReportPropertyChanging("idTipo");
                _idTipo = StructuralObject.SetValidValue(value, "idTipo");
                ReportPropertyChanged("idTipo");
                OnidTipoChanged();
            }
        }
        private global::System.Int32 _idTipo;
        partial void OnidTipoChanging(global::System.Int32 value);
        partial void OnidTipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataCadastro
        {
            get
            {
                return _DataCadastro;
            }
            private set
            {
                OnDataCadastroChanging(value);
                ReportPropertyChanging("DataCadastro");
                _DataCadastro = StructuralObject.SetValidValue(value, "DataCadastro");
                ReportPropertyChanged("DataCadastro");
                OnDataCadastroChanged();
            }
        }
        private global::System.DateTime _DataCadastro;
        partial void OnDataCadastroChanging(global::System.DateTime value);
        partial void OnDataCadastroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        private global::System.Int32 idEstado
        {
            get
            {
                return _idEstado;
            }
            set
            {
                OnidEstadoChanging(value);
                ReportPropertyChanging("idEstado");
                _idEstado = StructuralObject.SetValidValue(value, "idEstado");
                ReportPropertyChanged("idEstado");
                OnidEstadoChanged();
            }
        }
        private global::System.Int32 _idEstado;
        partial void OnidEstadoChanging(global::System.Int32 value);
        partial void OnidEstadoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "EventoGrupo", "Grupo")]
        public Grupo Grupo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("Model.EventoGrupo", "Grupo").Value;
            }
            private set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("Model.EventoGrupo", "Grupo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Grupo> GrupoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("Model.EventoGrupo", "Grupo");
            }
            private set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Grupo>("Model.EventoGrupo", "Grupo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "EventoConflito", "Conflito")]
        public EntityCollection<Conflito> ListaInternaConflitos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Conflito>("Model.EventoConflito", "Conflito");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Conflito>("Model.EventoConflito", "Conflito", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "EventoReserva", "Reserva")]
        public EntityCollection<Reserva> ListaInternaReservasdeLocais
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reserva>("Model.EventoReserva", "Reserva");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reserva>("Model.EventoReserva", "Reserva", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "EventoPublicoAlvo", "PublicoAlvo")]
        public EntityCollection<PublicoAlvo> ListaInternaPublicosAlvo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PublicoAlvo>("Model.EventoPublicoAlvo", "PublicoAlvo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PublicoAlvo>("Model.EventoPublicoAlvo", "PublicoAlvo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Grupo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Grupo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Grupo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        public static Grupo CreateGrupo(global::System.Int16 id, global::System.String nome)
        {
            Grupo grupo = new Grupo();
            grupo.Id = id;
            grupo.Nome = nome;
            return grupo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Id
        {
            get
            {
                return _Id;
            }
            protected set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int16 _Id;
        partial void OnIdChanging(global::System.Int16 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            private set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false, "Nome");
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "GrupoGrupo", "Grupo1")]
        public EntityCollection<Grupo> ListaInternaGruposFilhos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Grupo>("Model.GrupoGrupo", "Grupo1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Grupo>("Model.GrupoGrupo", "Grupo1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "GrupoGrupo", "Grupo")]
        public Grupo GrupoPai
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("Model.GrupoGrupo", "Grupo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("Model.GrupoGrupo", "Grupo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Grupo> GrupoPaiReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("Model.GrupoGrupo", "Grupo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Grupo>("Model.GrupoGrupo", "Grupo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Local")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Local : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Local object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        public static Local CreateLocal(global::System.Int16 id, global::System.String nome)
        {
            Local local = new Local();
            local.Id = id;
            local.Nome = nome;
            return local;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Id
        {
            get
            {
                return _Id;
            }
            protected set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int16 _Id;
        partial void OnIdChanging(global::System.Int16 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            private set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false, "Nome");
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="PublicoAlvo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PublicoAlvo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PublicoAlvo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        public static PublicoAlvo CreatePublicoAlvo(global::System.Int16 id, global::System.String nome)
        {
            PublicoAlvo publicoAlvo = new PublicoAlvo();
            publicoAlvo.Id = id;
            publicoAlvo.Nome = nome;
            return publicoAlvo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int16 _Id;
        partial void OnIdChanging(global::System.Int16 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false, "Nome");
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Reserva")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Reserva : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Reserva object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dataInicio">Initial value of the DataInicio property.</param>
        /// <param name="dataFim">Initial value of the DataFim property.</param>
        public static Reserva CreateReserva(global::System.Int64 id, global::System.DateTime dataInicio, global::System.DateTime dataFim)
        {
            Reserva reserva = new Reserva();
            reserva.Id = id;
            reserva.DataInicio = dataInicio;
            reserva.DataFim = dataFim;
            return reserva;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            protected set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataInicio
        {
            get
            {
                return _DataInicio;
            }
            private set
            {
                OnDataInicioChanging(value);
                ReportPropertyChanging("DataInicio");
                _DataInicio = StructuralObject.SetValidValue(value, "DataInicio");
                ReportPropertyChanged("DataInicio");
                OnDataInicioChanged();
            }
        }
        private global::System.DateTime _DataInicio;
        partial void OnDataInicioChanging(global::System.DateTime value);
        partial void OnDataInicioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataFim
        {
            get
            {
                return _DataFim;
            }
            private set
            {
                OnDataFimChanging(value);
                ReportPropertyChanging("DataFim");
                _DataFim = StructuralObject.SetValidValue(value, "DataFim");
                ReportPropertyChanged("DataFim");
                OnDataFimChanged();
            }
        }
        private global::System.DateTime _DataFim;
        partial void OnDataFimChanging(global::System.DateTime value);
        partial void OnDataFimChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "ReservaLocal", "Local")]
        public Local Local
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Local>("Model.ReservaLocal", "Local").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Local>("Model.ReservaLocal", "Local").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Local> LocalReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Local>("Model.ReservaLocal", "Local");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Local>("Model.ReservaLocal", "Local", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="SolicitacaoAcesso")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SolicitacaoAcesso : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SolicitacaoAcesso object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="ehCoordenador">Initial value of the EhCoordenador property.</param>
        /// <param name="dataCriacao">Initial value of the DataCriacao property.</param>
        /// <param name="idEstado">Initial value of the idEstado property.</param>
        public static SolicitacaoAcesso CreateSolicitacaoAcesso(global::System.Int32 id, global::System.Boolean ehCoordenador, global::System.DateTime dataCriacao, global::System.Int32 idEstado)
        {
            SolicitacaoAcesso solicitacaoAcesso = new SolicitacaoAcesso();
            solicitacaoAcesso.Id = id;
            solicitacaoAcesso.EhCoordenador = ehCoordenador;
            solicitacaoAcesso.DataCriacao = dataCriacao;
            solicitacaoAcesso.idEstado = idEstado;
            return solicitacaoAcesso;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            protected set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EhCoordenador
        {
            get
            {
                return _EhCoordenador;
            }
            private set
            {
                OnEhCoordenadorChanging(value);
                ReportPropertyChanging("EhCoordenador");
                _EhCoordenador = StructuralObject.SetValidValue(value, "EhCoordenador");
                ReportPropertyChanged("EhCoordenador");
                OnEhCoordenadorChanged();
            }
        }
        private global::System.Boolean _EhCoordenador;
        partial void OnEhCoordenadorChanging(global::System.Boolean value);
        partial void OnEhCoordenadorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataCriacao
        {
            get
            {
                return _DataCriacao;
            }
            private set
            {
                OnDataCriacaoChanging(value);
                ReportPropertyChanging("DataCriacao");
                _DataCriacao = StructuralObject.SetValidValue(value, "DataCriacao");
                ReportPropertyChanged("DataCriacao");
                OnDataCriacaoChanged();
            }
        }
        private global::System.DateTime _DataCriacao;
        partial void OnDataCriacaoChanging(global::System.DateTime value);
        partial void OnDataCriacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DataAvaliacao
        {
            get
            {
                return _DataAvaliacao;
            }
            private set
            {
                OnDataAvaliacaoChanging(value);
                ReportPropertyChanging("DataAvaliacao");
                _DataAvaliacao = StructuralObject.SetValidValue(value, "DataAvaliacao");
                ReportPropertyChanged("DataAvaliacao");
                OnDataAvaliacaoChanged();
            }
        }
        private Nullable<global::System.DateTime> _DataAvaliacao;
        partial void OnDataAvaliacaoChanging(Nullable<global::System.DateTime> value);
        partial void OnDataAvaliacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idEstado
        {
            get
            {
                return _idEstado;
            }
            private set
            {
                OnidEstadoChanging(value);
                ReportPropertyChanging("idEstado");
                _idEstado = StructuralObject.SetValidValue(value, "idEstado");
                ReportPropertyChanged("idEstado");
                OnidEstadoChanged();
            }
        }
        private global::System.Int32 _idEstado;
        partial void OnidEstadoChanging(global::System.Int32 value);
        partial void OnidEstadoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "SolicitacaoAcessoGrupo", "Grupo")]
        public Grupo Grupo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("Model.SolicitacaoAcessoGrupo", "Grupo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("Model.SolicitacaoAcessoGrupo", "Grupo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Grupo> GrupoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("Model.SolicitacaoAcessoGrupo", "Grupo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Grupo>("Model.SolicitacaoAcessoGrupo", "Grupo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="cPF">Initial value of the CPF property.</param>
        /// <param name="login">Initial value of the Login property.</param>
        /// <param name="senha">Initial value of the Senha property.</param>
        /// <param name="idEstado">Initial value of the idEstado property.</param>
        /// <param name="precisaTrocarSenha">Initial value of the PrecisaTrocarSenha property.</param>
        public static Usuario CreateUsuario(global::System.Int32 id, global::System.String nome, global::System.String email, global::System.String cPF, global::System.String login, global::System.String senha, global::System.Int32 idEstado, global::System.Boolean precisaTrocarSenha)
        {
            Usuario usuario = new Usuario();
            usuario.Id = id;
            usuario.Nome = nome;
            usuario.Email = email;
            usuario.CPF = cPF;
            usuario.Login = login;
            usuario.Senha = senha;
            usuario.idEstado = idEstado;
            usuario.PrecisaTrocarSenha = precisaTrocarSenha;
            return usuario;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            protected set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            private set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false, "Nome");
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            private set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false, "Email");
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CPF
        {
            get
            {
                return _CPF;
            }
            private set
            {
                OnCPFChanging(value);
                ReportPropertyChanging("CPF");
                _CPF = StructuralObject.SetValidValue(value, false, "CPF");
                ReportPropertyChanged("CPF");
                OnCPFChanged();
            }
        }
        private global::System.String _CPF;
        partial void OnCPFChanging(global::System.String value);
        partial void OnCPFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            private set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false, "Login");
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Senha
        {
            get
            {
                return _Senha;
            }
            private set
            {
                OnSenhaChanging(value);
                ReportPropertyChanging("Senha");
                _Senha = StructuralObject.SetValidValue(value, false, "Senha");
                ReportPropertyChanged("Senha");
                OnSenhaChanged();
            }
        }
        private global::System.String _Senha;
        partial void OnSenhaChanging(global::System.String value);
        partial void OnSenhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idEstado
        {
            get
            {
                return _idEstado;
            }
            private set
            {
                OnidEstadoChanging(value);
                ReportPropertyChanging("idEstado");
                _idEstado = StructuralObject.SetValidValue(value, "idEstado");
                ReportPropertyChanged("idEstado");
                OnidEstadoChanged();
            }
        }
        private global::System.Int32 _idEstado;
        partial void OnidEstadoChanging(global::System.Int32 value);
        partial void OnidEstadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PrecisaTrocarSenha
        {
            get
            {
                return _PrecisaTrocarSenha;
            }
            private set
            {
                OnPrecisaTrocarSenhaChanging(value);
                ReportPropertyChanging("PrecisaTrocarSenha");
                _PrecisaTrocarSenha = StructuralObject.SetValidValue(value, "PrecisaTrocarSenha");
                ReportPropertyChanged("PrecisaTrocarSenha");
                OnPrecisaTrocarSenhaChanged();
            }
        }
        private global::System.Boolean _PrecisaTrocarSenha;
        partial void OnPrecisaTrocarSenhaChanging(global::System.Boolean value);
        partial void OnPrecisaTrocarSenhaChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UsuarioSolicitacaoAcesso", "SolicitacaoAcesso")]
        public EntityCollection<SolicitacaoAcesso> ListaInternaSolicitacoesDeAcesso
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SolicitacaoAcesso>("Model.UsuarioSolicitacaoAcesso", "SolicitacaoAcesso");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SolicitacaoAcesso>("Model.UsuarioSolicitacaoAcesso", "SolicitacaoAcesso", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "UsuarioAtuacaoNoGrupo", "AtuacaoNoGrupo")]
        public EntityCollection<AtuacaoNoGrupo> ListaInternaAtuacoesNosGrupos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<AtuacaoNoGrupo>("Model.UsuarioAtuacaoNoGrupo", "AtuacaoNoGrupo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<AtuacaoNoGrupo>("Model.UsuarioAtuacaoNoGrupo", "AtuacaoNoGrupo", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
